# Site settings
title: Uniweb Module Builder
description: Standalone library for building federated modules for Uniweb CMS.
url: https://uniwebcms.github.io
baseurl: /uniweb-module-builder/

# Build settings
theme: midnight

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
